# https://wiki.postgresql.org/wiki/Apt
- name: Import PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    state: present

- name: Install dependencies
  apt:
    name: python3-psycopg2

- name: Install PostgreSQL
  apt:
    name: postgresql-{{ postgresql_version }}
